// <auto-generated />
using System;
using LessonApi.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LessonApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240221143432_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LessonApi.Models.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LessonPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 2, 21, 16, 34, 32, 715, DateTimeKind.Local).AddTicks(9152),
                            Description = "Olur olur",
                            LessonName = "Matematik",
                            LessonPrice = 400m
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 2, 21, 16, 34, 32, 715, DateTimeKind.Local).AddTicks(9167),
                            Description = "Kolay olur",
                            LessonName = "Türkçe",
                            LessonPrice = 200m
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 2, 21, 16, 34, 32, 715, DateTimeKind.Local).AddTicks(9169),
                            Description = "Zor olur",
                            LessonName = "Fizik",
                            LessonPrice = 400m
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 2, 21, 16, 34, 32, 715, DateTimeKind.Local).AddTicks(9169),
                            Description = " Biraz Zor",
                            LessonName = "Kimya",
                            LessonPrice = 300m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
